BACKUP DATABASE [YourDatabase] 
TO DISK = 'C:\Backups\YourDatabase_Partial.bak'
WITH PARTIAL;


BACKUP DATABASE DBNAME
TO DISK = 'YOURPATH'


BACKUP DATABASE DBNAME TO DISK='path' WITH INIT;
--YENİ DB YEDEĞİNİN ESKİ YEDEK ÜZERİNE YAZILMASI

BACKUP DATABASE DBNAME TO DISK='path' WITH DIFFERENTIAL;

BACKUP DATABASE DBNAME TO DISK='path' WITH STATS;
--YEDEKLEME İŞLEMİNİN GERÇEKLEŞME YÜZDESİ

BACKUP DATABASE DBNAME TO DISK='path' WITH STATS = 1;

BACKUP DATABASE DBNAME TO DISK='path' WITH DESCRIPTION = "AÇIKLAMA";


RESTORE FILELISTONLY FROM DISK = 'path';
BACKUP LOG DBDENEME TO DISK = 'path' WITH STATS;

BACKUP LOG DBDENEME TO DISK = 'path' WITH DESCRIPTION = 'DENEME';

DROP DATABASE DBDENEME;

RESTORE DATABASE DBDENEME FROM DISK = 'deneme';