CREATE DATABASE SATISVT
use SATISVT

CREATE TABLE TBLKATEGORI
(
KATEGORIID tinyint identity(1,1) primary key,
KATEGORIAD varchar(50)
)


CREATE TABLE TBLURUNLER
(
URUNID int identity(1,1) primary key,
URUNAD varchar(50),
URUNMARKA varchar(50),
KATEGORI tinyint,
URUNALISFIYAT decimal(18,2),
URUNSATISFIYAT decimal(18,2),
URUNSTOK smallint check(URUNSTOK>0),
URUNDURUM bit default '1'
)

CREATE TABLE TBLPERSONEL
(
PERSONELID smallint identity(1,1) primary key,
PERSONELADSOYAD varchar(50)
)

CREATE TABLE TBLMUSTERI
(
MUSTERIID int primary key identity(1,1),
MUSTERIAD varchar(50),
MUSTERISOYAD varchar(50),
MUSTERISEHIR varchar(13),
MUSTERIBAKIYE decimal(18,2)
)


CREATE TABLE TBLHAREKET
(
HAREKETID int primary key identity(1,1), --identity(1,1) ile HAREKETID sütunu otomatik artan olarak ayarlandı
URUN int,
MUSTERI int,
PERSONEL smallint,
ADET int,
TUTAR decimal(18,2),
TARIH smalldatetime
)

TRUNCATE TABLE TBLURUNLER

--***********************************************************************************************************

INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('BILGISAYAR')

INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('BEYAZ EŞYA')

INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('KÜÇÜK EV ALETİ')

INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('TV')


INSERT INTO TBLURUNLER (URUNAD,URUNMARKA,KATEGORI,URUNALISFIYAT,URUNSATISFIYAT,URUNSTOK)
VALUES ('BUZDOLABI','SIEMENS',2,4356,4588,10)


--***********************************************************************************************************
use SATISVT
UPDATE TBLURUNLER SET URUNAD='KETTLE' WHERE URUNAD='SU ISITICI'

SELECT KATEGORIAD,COUNT(*) AS 'TOPLAM ÜRÜN' 
FROM TBLURUNLER INNER JOIN TBLKATEGORI 
ON TBLURUNLER.KATEGORI=TBLKATEGORI.KATEGORIID GROUP BY KATEGORIAD
ORDER BY COUNT(*)

UPDATE TBLURUNLER SET URUNSATISFIYAT+=500 WHERE KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BILGISAYAR')
SELECT * FROM TBLURUNLER

SELECT COUNT(*) AS 'Kaç farklı ürün',SUM(URUNSTOK) AS 'STOK SAYISI' FROM TBLURUNLER


SELECT URUNID,URUNAD,URUNMARKA,KATEGORIAD,URUNSATISFIYAT,URUNALISFIYAT,
(URUNSATISFIYAT-URUNALISFIYAT) AS 'KAR'
FROM TBLURUNLER 
INNER JOIN TBLKATEGORI ON TBLURUNLER.KATEGORI=TBLKATEGORI.KATEGORIID


SELECT URUNID,URUNAD,URUNMARKA,KATEGORIAD,URUNSATISFIYAT,URUNALISFIYAT,URUNSTOK,
(URUNSATISFIYAT-URUNALISFIYAT) AS 'KAR',(URUNSATISFIYAT-URUNALISFIYAT)*URUNSTOK AS 'TOPLAM KAR'
FROM TBLURUNLER 
INNER JOIN TBLKATEGORI ON TBLURUNLER.KATEGORI=TBLKATEGORI.KATEGORIID























