create table TBLDERSLER
(
DERSID tinyint,
DERSAD varchar(20)
)

ALTER TABLE TBLDERSLER ADD KONTENJAN smallint   --KONTENJAN isimli sütun ekler

ALTER TABLE Personeller
ADD CONSTRAINT UQ_PersonelEmail
UNIQUE (Email)


ALTER TABLE TBLDERSLER DROP COLUMN KONTENJAN    --KONTENJAN isimli sütunu siler

SELECT * FROM TBLOGRENCILER

SELECT OGRAD,OGRSOYAD FROM TBLOGRENCILER

SELECT OGRSEHIR FROM TBLOGRENCILER

SELECT OGRAD FROM TBLOGRENCILER WHERE OGRID=5

SELECT * FROM TBLOGRENCILER WHERE OGRAD='Ali'

SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR='Adana' AND OGRKULUP='Kitaplık'

SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR='Adana' OR OGRKULUP='Kitaplik'

SELECT * FROM TBLNOTLAR

SELECT (SINAV1+SINAV2+SINAV3) FROM TBLNOTLAR

SELECT (SINAV1+SINAV2+SINAV3)/3 FROM TBLNOTLAR

INSERT INTO TBLOGRENCILER(OGRAD,OGRSOYAD,OGRSEHIR) VALUES ('Baran','Yücedağ','Elazığ')

INSERT INTO TBLNOTLAR (OGRENCI,DERS,SINAV1,SINAV3) VALUES (6,2,88,67)

DELETE FROM TBLDERSLER  --tablodaki bütün değerleri siler

DELETE FROM TBLDERSLER WHERE DERSID=3

DELETE FROM TBLDERSLER WHERE DERSAD='Algoritma'

TRUNCATE TABLE TBLDERSLER  --tabloyu sıfırlar

UPDATE TBLOGRENCILER SET OGRCINSIYET='Erkek'

UPDATE TBLOGRENCILER SET OGRCINSIYET='Kız' WHERE OGRID=2

UPDATE TBLOGRENCILER SET OGRCINSIYET='Kız' WHERE OGRID=3 OR OGRID=4

UPDATE TBLOGRENCILER SET OGRKULUP='Kitaplık' where OGRAD='Baran'

UPDATE TBLNOTLAR SET DERS=2

INSERT INTO TBLNOTLAR (OGRENCI,DERS,SINAV1,SINAV2) VALUES (2,2,45,99)

UPDATE TBLNOTLAR SET ORTALAMA=(SINAV1+SINAV2+SINAV3)/3

UPDATE TBLNOTLAR SET DURUM=1 WHERE ORTALAMA>=50
UPDATE TBLNOTLAR SET DURUM=0 WHERE ORTALAMA<=50


ALTER TABLE Personeller
ADD CONSTRAINT DC_KayitTarih DEFAULT GETDATE() FOR KayitTarih


ALTER TABLE Personeller
ADD CONSTRAINT DC_Sehir DEFAULT 'Tan�ms�z' FOR Sehir


--	Check Constraint


CREATE TABLE Kullanicilar
(
	KullaniciID		INT PRIMARY KEY NOT NULL,
	KullaniciAd		VARCHAR(20) NOT NULL,
	Sifre			VARCHAR(15) NOT NULL,
	Email			VARCHAR(40) NOT NULL,
	Telefon		VARCHAR(11) NOT NULL
);



ALTER TABLE Kullanicilar
ADD CONSTRAINT CHK_SifreUzunluk CHECK(LEN(Sifre) >= 5 AND LEN(Sifre) <= 15)


ALTER TABLE Kullanicilar
ADD CONSTRAINT CHK_Email CHECK(CHARINDEX('@', Email) > 0 OR Email IS NULL)



ALTER TABLE Makaleler
ADD CONSTRAINT FK_MakaleKategoriler
FOREIGN KEY(KategoriID) REFERENCES Kategoriler(KategoriID)



ALTER TABLE Kullanicilar
WITH NO CHECK
ADD CONSTRAINT CHK_Telefon CHECK(
Telefon IS NULL OR(
Telefon LIKE '[0][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') 
AND LEN(Telefon) = 14)


--	Constraint'i Ge�ici Olarak Devre D��� B�rakmak


ALTER TABLE Kullanicilar
NOCHECK
CONSTRAINT CHK_Telefon
















