--SELECT 20+4 As 'Toplam',20-4 as 'Fark', 20*4 As 'Çarpım', 20/4 As 'Bölüm'

--SELECT * FROM TBLNOTLAR WHERE DERS=1

--UPDATE TBLNOTLAR SET SINAV2=SINAV2+10 FROM TBLNOTLAR WHERE DERS=1

UPDATE TBLNOTLAR SET SINAV2=100 WHERE SINAV2>100

SELECT * FROM TBLNOTLAR WHERE DERS=1

SELECT AVG(ORTALAMA) FROM TBLNOTLAR WHERE DERS=1


******************************************************************************************************


--SELECT ABS(-86) AS 'MUTLAK'
--SELECT POWER(2,4) AS 'ÜSLÜ DEĞERİ'
--SELECT POWER(SINAV1,2) FROM TBLNOTLAR
--SELECT SQRT(786) AS 'KAREKÖK'

SELECT FLOOR(4.86) AS 'TABAN',CEILING(4.86) AS 'TAVAN'

******************************************************************************************************


--SELECT SUM(SINAV1) FROM TBLNOTLAR WHERE OGRENCI=1
--SELECT SINAV1,DERS FROM TBLNOTLAR WHERE OGRENCI=1

SELECT DERSAD,SINAV1 FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS=TBLDERSLER.DERSID WHERE OGRENCI=1

SELECT DERSAD,SINAV1 FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS=TBLDERSLER.DERSID WHERE OGRENCI=(SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD='Ayşe' AND OGRSOYAD='ÇINAR')
