SELECT OGRSEHIR,Count(*) as 'Toplam' FROM TBLOGRENCILER GROUP BY OGRSEHIR

SELECT OGRCINSIYET,COUNT(*) As 'Toplam' FROM TBLOGRENCILER GROUP BY OGRCINSIYET

UPDATE TBLNOTLAR SET ORTALAMA=(SINAV1+SINAV2+SINAV3)/3

UPDATE TBLNOTLAR SET DURUM=0 WHERE ORTALAMA<=50

SELECT OGRKULUP,COUNT(*) FROM TBLOGRENCILER GROUP BY OGRKULUP

--------------------------------------------------

SELECT OGRSEHIR,COUNT(*) AS 'SAYI' FROM TBLOGRENCILER GROUP BY OGRSEHIR HAVING COUNT(*)=2

SELECT OGRKULUP,COUNT(*) FROM TBLOGRENCILER GROUP BY OGRKULUP HAVING OGRKULUP='Kitaplık'

--------------------------------------------------

SELECT * FROM TBLOGRENCILER WHERE OGRAD LIKE '%z%' AND OGRSEHIR LIKE '%i%'

SELECT * FROM TBLOGRENCILER WHERE OGRAD LIKE 'a%'

SELECT * FROM TBLOGRENCILER WHERE OGRAD LIKE '%ı'

SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR LIKE '%ar%'

SELECT * FROM TBLOGRENCILER WHERE OGRKULUP NOT LIKE '%i%'

--------------------------------------------------

SELECT OGRSEHIR FROM TBLOGRENCILER

SELECT DISTINCT OGRSEHIR FROM TBLOGRENCILER

SELECT COUNT(DISTINCT(OGRSEHIR)) FROM TBLOGRENCILER

SELECT DISTINCT OGRKULUP FROM TBLOGRENCILER

SELECT COUNT(DISTINCT(OGRKULUP)) FROM TBLOGRENCILER

--------------------------------------------------


SELECT * FROM TBLOGRENCILER ORDER BY OGRAD
--default olarak ASC

SELECT * FROM TBLOGRENCILER ORDER BY OGRAD ASC

SELECT * FROM TBLOGRENCILER ORDER BY OGRAD DESC

SELECT DISTINCT OGRSEHIR FROM TBLOGRENCILER ORDER BY OGRSEHIR DESC


--------------------------------------------------

SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR LIKE '%ir%'

SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR LIKE '%ir_%'

SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR LIKE '%an_%'

SELECT * FROM TBLOGRENCILER WHERE OGRAD LIKE '[A,B]%'

SELECT * FROM TBLOGRENCILER WHERE OGRAD LIKE '%[A,B]%'

SELECT * FROM TBLOGRENCILER WHERE OGRAD LIKE '%[A,B]'

SELECT * FROM TBLOGRENCILER WHERE OGRKULUP LIKE '[a-m]%'

SELECT * FROM TBLOGRENCILER WHERE OGRKULUP LIKE '%[a-e]'

--------------------------------------------------

SELECT * FROM TBLOGRENCILER WHERE OGRID<=3

SELECT TOP 3 * FROM TBLOGRENCILER

SELECT TOP 4 * FROM TBLOGRENCILER ORDER BY OGRID DESC

SELECT TOP 65 PERCENT * FROM TBLOGRENCILER

--------------------------------------------------

SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR in('İzmir','Ankara','Edirne')

SELECT * FROM TBLNOTLAR WHERE SINAV1 in(70,75,80,85,90)

SELECT * FROM TBLNOTLAR WHERE SINAV1 NOT in(70,75,80,85,90)

--------------------------------------------------

SELECT * FROM TBLNOTLAR WHERE ORTALAMA BETWEEN 74 AND 100

SELECT * FROM TBLOGRENCILER WHERE OGRAD BETWEEN 'A' AND 'K'  --adı A-K arası harflerle başlayanlar

SELECT * FROM TBLOGRENCILER WHERE OGRAD NOT BETWEEN 'A' AND 'K'















