BEGIN TRANSACTION
INSERT INTO TBLKATEGORI(AD) VALUES ('TV')
INSERT INTO TBLKATEGORI (AD) VALUES ('HALI')
SELECT * FROM TBLKATEGORI
ROLLBACK


BEGIN TRANSACTION
INSERT INTO TBLURUN (URUNAD,STOK) VALUES ('ÜRÜN1',25)
INSERT INTO TBLURUN (AD,STOK) VALUES ('ÜRÜN2',40)
SELECT * FROM TBLURUN
COMMIT