UPDATE TBLSTOK SET TOPLAMURUN=(
SELECT COUNT(*) FROM TBLURUN
)

CREATE TRIGGER ARTTIR ON TBLURUN
AFTER INSERT AS UPDATE TBLSTOK SET TOPLAMURUN+=1

UPDATE TBLSTOK SET TOPLAMURUN=(SELECT SUM(STOK) FROM TBLURUN)

DROP TRIGGER ARTTIR


CREATE TRIGGER ARTTIR ON TBLURUN
AFTER INSERT AS DECLARE @STOKSAYI INT
SELECT @STOKSAYI=STOK FROM INSERTED
UPDATE TBLSTOK SET TOPLAMURUN+=@STOKSAYI

CREATE TRIGGER AZALT
ON TBLURUN
AFTER DELETE
AS
DECLARE @STOKSAYI INT
SELECT @STOKSAYI=STOK FROM DELETED
UPDATE TBLSTOK SET TOPLAMURUN=@TOPLAMURUN-@STOKSAYI


INSERT INTO TBLURUN(AD,STOK) VALUES('MIXER',80)

















