BEGIN TRANSACTION 
    SAVE TRANSACTION firstTransaction
    --İŞLEMLER
    ROLLBACK TRAN firstTransaction
    --İŞLEMLER
    ROLLBACK TRAN firstTransaction
    --İŞLEMLER
    COMMIT TRANSACTION firstTransaction
END TRANSACTION

--ACID = -ATOMICITY CONSISTENCY ISOLATION DURABILITY